<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>cd5f922f-dc4d-4196-b72b-7a6a245ca5bc</testSuiteGuid>
   <testCaseLink>
      <guid>dd69c6d2-96bf-4bd4-a7c3-89918b8d3738</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/List_Users</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c80f577-a84d-4744-aac3-78bce8e705c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e41e63a-2c97-4c51-9a83-78fe3827abd3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Single_User</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bd4bd1a-3f4c-4d2f-8dc3-2257bea121f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3584671-8186-4e9f-b84b-aeb044e8ab8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Put_Update</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>158157a9-08d6-4cf6-b9c9-86fc3588a217</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2a3562b-c8cd-41ff-9078-c0c2a18bd8c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Register_Successful</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5daafe7c-a939-42af-b189-2836a762e411</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
